# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true
     
    - name: Cache golangci-lint
      uses: actions/cache@v3
      with:
        path: ~/.cache/golangci-lint
        key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-golangci-lint-

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest 
        args: --timeout=2m --fast
        skip-cache: false
        skip-pkg-cache: false
        skip-build-cache: false

    - name: Test
      run: go test -v ./... -timeout=30s
